name: Deprecate package

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to deprecate
        required: true
      version_range:
        description: The version range to deprecate
        required: true
      message:
        description: The deprecation message
        required: true

permissions: write-all

jobs:
  deprecate:
    uses: ./.github/workflows/npm-publish.yaml
    with:
      mode: deprecate
      package: ${{ github.event.inputs.package }}
      version_range: ${{ github.event.inputs.version_range }}
      message: ${{ github.event.inputs.message }}
    secrets: inherit
