name: Nightly build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  nightly:
    uses: ./.github/workflows/npm-publish.yaml
    with:
      mode: nightly
    secrets: inherit
